-- Insert sample customers with extended data
-- This includes the VECTOR 3 customer and additional test customers

-- Insert VECTOR 3 customer with complete extended data
INSERT INTO customers (
  id,
  name,
  email,
  phone,
  tax_id,
  address,
  city,
  postal_code,
  province,
  country,
  sector,
  contact_person,
  website,
  notes,
  is_active,
  verifactu_status,
  
  -- Extended fields
  commercial_name,
  legal_form,
  registration_number,
  registration_date,
  share_capital,
  administrator,
  administrator_nif,
  business_activity,
  cnae_code,
  employees_count,
  annual_revenue,
  credit_limit,
  payment_terms,
  preferred_payment_method,
  bank_account,
  swift_code,
  tax_regime,
  vat_number,
  social_security_number,
  mutual_insurance,
  risk_level,
  customer_since,
  last_order_date,
  total_orders,
  average_order_value,
  
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  'VECTOR 3 SISTEMAS INFORMÁTICOS S.L.',
  'info@vector3.es',
  '+34 91 123 45 67',
  'B12345678',
  'Calle Tecnología, 123, 2º A',
  'Madrid',
  '28001',
  'Madrid',
  'España',
  'Tecnología',
  'Carlos Rodríguez',
  'https://www.vector3.es',
  'Cliente premium especializado en desarrollo de software empresarial. Excelente historial de pagos.',
  true,
  'pending',
  
  -- Extended data
  'Vector3 Tech',
  'Sociedad Limitada (SL)',
  'M-123456',
  '2015-03-15',
  50000.00,
  'Carlos Rodríguez García',
  '12345678A',
  'Desarrollo de software y consultoría tecnológica',
  '6201',
  25,
  850000.00,
  25000.00,
  30,
  'Transferencia bancaria',
  'ES91 2100 0418 4502 0005 1332',
  'CAIXESBB',
  'Régimen General',
  'ESB12345678',
  '281234567890',
  'Mutua Universal',
  'low',
  '2020-01-15',
  '2024-11-15',
  47,
  5320.50,
  
  NOW(),
  NOW()
) ON CONFLICT (tax_id) DO UPDATE SET
  name = EXCLUDED.name,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  address = EXCLUDED.address,
  city = EXCLUDED.city,
  postal_code = EXCLUDED.postal_code,
  province = EXCLUDED.province,
  country = EXCLUDED.country,
  sector = EXCLUDED.sector,
  contact_person = EXCLUDED.contact_person,
  website = EXCLUDED.website,
  notes = EXCLUDED.notes,
  commercial_name = EXCLUDED.commercial_name,
  legal_form = EXCLUDED.legal_form,
  registration_number = EXCLUDED.registration_number,
  registration_date = EXCLUDED.registration_date,
  share_capital = EXCLUDED.share_capital,
  administrator = EXCLUDED.administrator,
  administrator_nif = EXCLUDED.administrator_nif,
  business_activity = EXCLUDED.business_activity,
  cnae_code = EXCLUDED.cnae_code,
  employees_count = EXCLUDED.employees_count,
  annual_revenue = EXCLUDED.annual_revenue,
  credit_limit = EXCLUDED.credit_limit,
  payment_terms = EXCLUDED.payment_terms,
  preferred_payment_method = EXCLUDED.preferred_payment_method,
  bank_account = EXCLUDED.bank_account,
  swift_code = EXCLUDED.swift_code,
  tax_regime = EXCLUDED.tax_regime,
  vat_number = EXCLUDED.vat_number,
  social_security_number = EXCLUDED.social_security_number,
  mutual_insurance = EXCLUDED.mutual_insurance,
  risk_level = EXCLUDED.risk_level,
  customer_since = EXCLUDED.customer_since,
  last_order_date = EXCLUDED.last_order_date,
  total_orders = EXCLUDED.total_orders,
  average_order_value = EXCLUDED.average_order_value,
  updated_at = NOW();

-- Insert additional test customers
INSERT INTO customers (
  id,
  name,
  email,
  phone,
  tax_id,
  address,
  city,
  postal_code,
  province,
  country,
  sector,
  contact_person,
  website,
  is_active,
  verifactu_status,
  commercial_name,
  legal_form,
  business_activity,
  employees_count,
  annual_revenue,
  credit_limit,
  payment_terms,
  preferred_payment_method,
  risk_level,
  customer_since,
  total_orders,
  average_order_value,
  created_at,
  updated_at
) VALUES 
-- Construcciones García
(
  gen_random_uuid(),
  'CONSTRUCCIONES GARCÍA S.A.',
  'admin@construccionesgarcia.com',
  '+34 95 234 56 78',
  'A87654321',
  'Polígono Industrial Sur, Nave 15',
  'Sevilla',
  '41020',
  'Sevilla',
  'España',
  'Construcción',
  'María García López',
  'https://www.construccionesgarcia.com',
  true,
  'synced',
  'García Construcciones',
  'Sociedad Anónima (SA)',
  'Construcción de edificios residenciales y comerciales',
  45,
  1200000.00,
  50000.00,
  60,
  'Domiciliación bancaria',
  'medium',
  '2018-06-20',
  23,
  8750.25,
  NOW(),
  NOW()
),

-- Comercial Alimentaria
(
  gen_random_uuid(),
  'COMERCIAL ALIMENTARIA DEL SUR S.L.',
  'ventas@alimentariadelsur.es',
  '+34 96 345 67 89',
  'B23456789',
  'Mercado Central, Puesto 45-47',
  'Valencia',
  '46001',
  'Valencia',
  'España',
  'Alimentación',
  'José Martínez Ruiz',
  NULL,
  true,
  'error',
  'Alimentaria Sur',
  'Sociedad Limitada (SL)',
  'Distribución de productos alimentarios',
  12,
  450000.00,
  15000.00,
  15,
  'Transferencia bancaria',
  'high',
  '2021-09-10',
  156,
  1250.75,
  NOW(),
  NOW()
),

-- Consultoría Empresarial
(
  gen_random_uuid(),
  'RAMÓN LÓPEZ CONSULTORÍA',
  'ramon.lopez@consultoria-rl.com',
  '+34 93 456 78 90',
  '12345678Z',
  'Paseo de Gracia, 85, 3º 2ª',
  'Barcelona',
  '08008',
  'Barcelona',
  'España',
  'Servicios',
  'Ramón López Fernández',
  'https://www.consultoria-rl.com',
  true,
  'simulated',
  NULL,
  'Autónomo',
  'Consultoría empresarial y asesoramiento fiscal',
  1,
  85000.00,
  5000.00,
  30,
  'Transferencia bancaria',
  'low',
  '2022-02-14',
  34,
  2100.00,
  NOW(),
  NOW()
);

-- Update statistics for existing customers
UPDATE customers SET 
  total_orders = FLOOR(RANDOM() * 50) + 1,
  average_order_value = ROUND((RANDOM() * 5000 + 500)::numeric, 2),
  last_order_date = CURRENT_DATE - INTERVAL '1 day' * FLOOR(RANDOM() * 90)
WHERE total_orders IS NULL OR total_orders = 0;

COMMIT;
